
import type { Question } from './types';

export const ALL_QUESTIONS: Question[] = [
  {
    id: 1,
    question: "What is the supreme law of the land?",
    answer: "the Constitution",
    topic: "Principles of American Democracy",
  },
  {
    id: 2,
    question: "What does the Constitution do?",
    answer: "sets up the government",
    topic: "Principles of American Democracy",
  },
  {
    id: 3,
    question: "The idea of self-government is in the first three words of the Constitution. What are these words?",
    answer: "We the People",
    topic: "Principles of American Democracy",
  },
  {
    id: 4,
    question: "What is an amendment?",
    answer: "a change to the Constitution",
    topic: "Principles of American Democracy",
  },
  {
    id: 5,
    question: "What do we call the first ten amendments to the Constitution?",
    answer: "the Bill of Rights",
    topic: "Principles of American Democracy",
  },
  {
    id: 6,
    question: "What is one right or freedom from the First Amendment?",
    answer: "speech",
    topic: "Principles of American Democracy",
  },
  {
    id: 7,
    question: "How many amendments does the Constitution have?",
    answer: "27",
    topic: "System of Government",
  },
  {
    id: 8,
    question: "What did the Declaration of Independence do?",
    answer: "declared our independence",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 9,
    question: "What are two rights in the Declaration of Independence?",
    answer: "life, pursuit of happiness",
    topic: "Principles of American Democracy",
  },
  {
    id: 10,
    question: "What is freedom of religion?",
    answer: "You can practice any religion, or not practice a religion",
    topic: "Principles of American Democracy",
  },
  {
    id: 11,
    question: "What is the economic system in the United States?",
    answer: "capitalist economy",
    topic: "Integrated Civics",
  },
  {
    id: 12,
    question: "What is the “rule of law”?",
    answer: "Everyone must follow the law",
    topic: "Principles of American Democracy",
  },
  {
    id: 13,
    question: "Name one branch or part of the government.",
    answer: "Congress",
    topic: "System of Government",
  },
  {
    id: 14,
    question: "What stops one branch of government from becoming too powerful?",
    answer: "checks and balances",
    topic: "System of Government",
  },
  {
    id: 15,
    question: "Who is in charge of the executive branch?",
    answer: "the President",
    topic: "System of Government",
  },
  {
    id: 16,
    question: "Who makes federal laws?",
    answer: "Congress",
    topic: "System of Government",
  },
  {
    id: 17,
    question: "What are the two parts of the U.S. Congress?",
    answer: "the Senate and House of Representatives",
    topic: "System of Government",
  },
  {
    id: 18,
    question: "How many U.S. Senators are there?",
    answer: "100",
    topic: "System of Government",
  },
  {
    id: 19,
    question: "We elect a U.S. Senator for how many years?",
    answer: "6 years",
    topic: "System of Government",
  },
  {
    id: 20,
    question: "Who is one of your state’s U.S. Senators now?",
    answer: "Alex Padilla",
    topic: "System of Government",
  },
  {
    id: 21,
    question: "The House of Representatives has how many voting members?",
    answer: "435",
    topic: "System of Government",
  },
  {
    id: 22,
    question: "We elect a U.S. Representative for how many years?",
    answer: "2 years",
    topic: "System of Government",
  },
  {
    id: 23,
    question: "Name your U.S. Representative.",
    answer: "Sam Liccardo",
    topic: "System of Government",
  },
  {
    id: 24,
    question: "Who does a U.S. Senator represent?",
    answer: "all people of the state",
    topic: "System of Government",
  },
  {
    id: 25,
    question: "Why do some states have more Representatives than other states?",
    answer: "because they have more people",
    topic: "System of Government",
  },
  {
    id: 26,
    question: "We elect a President for how many years?",
    answer: "4 years",
    topic: "System of Government",
  },
  {
    id: 27,
    question: "In what month do we vote for President?",
    answer: "in November",
    topic: "System of Government",
  },
  {
    id: 28,
    question: "What is the name of the President of the United States now?",
    answer: "Donald Trump",
    topic: "Integrated Civics",
  },
  {
    id: 29,
    question: "What is the name of the Vice President of the United States now?",
    answer: "JD Vance",
    topic: "System of Government",
  },
  {
    id: 30,
    question: "If the President can no longer serve, who becomes President?",
    answer: "the Vice President",
    topic: "System of Government",
  },
  {
    id: 31,
    question: "If both the President and the Vice President can no longer serve, who becomes President?",
    answer: "the Speaker of the House",
    topic: "System of Government",
  },
  {
    id: 32,
    question: "Who is the Commander in Chief of the military?",
    answer: "the President",
    topic: "System of Government",
  },
  {
    id: 33,
    question: "Who signs bills to become laws?",
    answer: "the President",
    topic: "System of Government",
  },
  {
    id: 34,
    question: "Who vetoes bills?",
    answer: "the President",
    topic: "System of Government",
  },
  {
    id: 35,
    question: "What does the President’s Cabinet do?",
    answer: "advises the President",
    topic: "System of Government",
  },
  {
    id: 36,
    question: "What are two Cabinet-level positions?",
    answer: "Secretary of Education, Secretary of Labor",
    topic: "System of Government",
  },
  {
    id: 37,
    question: "What does the judicial branch do?",
    answer: "reviews laws",
    topic: "System of Government",
  },
  {
    id: 38,
    question: "What is the highest court in the United States?",
    answer: "the Supreme Court",
    topic: "System of Government",
  },
  {
    id: 39,
    question: "How many justices are on the Supreme Court?",
    answer: "9 justices",
    topic: "System of Government",
  },
  {
    id: 40,
    question: "Who is the Chief Justice of the United States now?",
    answer: "John Roberts",
    topic: "System of Government",
  },
  {
    id: 41,
    question: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
    answer: "to print money",
    topic: "System of Government",
  },
  {
    id: 42,
    question: "Under our Constitution, some powers belong to the states. What is one power of the states?",
    answer: "provide schooling and education",
    topic: "System of Government",
  },
  {
    id: 43,
    question: "Who is the Governor of your state now?",
    answer: "Gavin Newsom",
    topic: "Integrated Civics",
  },
  {
    id: 44,
    question: "What is the capital of your state?",
    answer: "Sacramento",
    topic: "System of Government",
  },
  {
    id: 45,
    question: "What are the two major political parties in the United States?",
    answer: "Democratic and Republican",
    topic: "Integrated Civics",
  },
  {
    id: 46,
    question: "What is the political party of the President now?",
    answer: "Republican",
    topic: "Integrated Civics",
  },
  {
    id: 47,
    question: "What is the name of the Speaker of the House of Representatives now?",
    answer: "Mike Johnson",
    topic: "System of Government",
  },
  {
    id: 48,
    question: "There are four amendments to the Constitution about who can vote. Describe one of them.",
    answer: "Citizens 18 and older can vote",
    topic: "Rights and Responsibilities",
  },
  {
    id: 49,
    question: "What is one responsibility that is only for United States citizens?",
    answer: "to vote in a federal election",
    topic: "Rights and Responsibilities",
  },
  {
    id: 50,
    question: "Name one right only for United States citizens.",
    answer: "to vote in a federal election",
    topic: "Rights and Responsibilities",
  },
  {
    id: 51,
    question: "What are two rights of everyone living in the United States?",
    answer: "freedom of speech, freedom of religion",
    topic: "Rights and Responsibilities",
  },
  {
    id: 52,
    question: "What do we show loyalty to when we say the Pledge of Allegiance?",
    answer: "to the United States and the flag",
    topic: "Integrated Civics",
  },
  {
    id: 53,
    question: "What is one promise you make when you become a United States citizen?",
    answer: "obey the laws of the United States",
    topic: "Rights and Responsibilities",
  },
  {
    id: 54,
    question: "How old do citizens have to be to vote for President?",
    answer: "18 years old",
    topic: "Rights and Responsibilities",
  },
  {
    id: 55,
    question: "What are two ways that Americans can participate in their democracy?",
    answer: "to vote and run for office",
    topic: "Rights and Responsibilities",
  },
  {
    id: 56,
    question: "When is the last day you can send in federal income tax forms?",
    answer: "April 15",
    topic: "Integrated Civics",
  },
  {
    id: 57,
    question: "When must all men register for the Selective Service?",
    answer: "between eighteen (18) and twenty-six (26)",
    topic: "Rights and Responsibilities",
  },
  {
    id: 58,
    question: "What is one reason colonists came to America?",
    answer: "religious freedom",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 59,
    question: "Who lived in America before the Europeans arrived?",
    answer: "Native Americans",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 60,
    question: "What group of people was taken to America and sold as slaves?",
    answer: "Africans",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 61,
    question: "Why did the colonists fight the British?",
    answer: "because of high taxes",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 62,
    question: "Who wrote the Declaration of Independence?",
    answer: "Thomas Jefferson",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 63,
    question: "When was the Declaration of Independence adopted?",
    answer: "July 4, 1776",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 64,
    question: "There were 13 original states. Name three.",
    answer: "New York, New Jersey, Delaware",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 65,
    question: "What happened at the Constitutional Convention?",
    answer: "The Constitution was written.",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 66,
    question: "When was the Constitution written?",
    answer: "1787",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 67,
    question: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
    answer: "Alexander Hamilton",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 68,
    question: "What is one thing Benjamin Franklin is famous for?",
    answer: "he started the first free libraries",
    topic: "American History: Recent and Other",
  },
  {
    id: 69,
    question: "Who is the “Father of Our Country”?",
    answer: "George Washington",
    topic: "American History: Recent and Other",
  },
  {
    id: 70,
    question: "Who was the first President?",
    answer: "George Washington",
    topic: "American History: Recent and Other",
  },
  {
    id: 71,
    question: "What territory did the United States buy from France in 1803?",
    answer: "the Louisiana Territory",
    topic: "American History: 1800s",
  },
  {
    id: 72,
    question: "Name one war fought by the United States in the 1800s.",
    answer: "Mexican-American War",
    topic: "American History: 1800s",
  },
  {
    id: 73,
    question: "Name the U.S. war between the North and the South.",
    answer: "the Civil War",
    topic: "American History: 1800s",
  },
  {
    id: 74,
    question: "Name one problem that led to the Civil War.",
    answer: "slavery",
    topic: "American History: 1800s",
  },
  {
    id: 75,
    question: "What was one important thing that Abraham Lincoln did?",
    answer: "freed the slaves (Emancipation Proclamation)",
    topic: "American History: Recent and Other",
  },
  {
    id: 76,
    question: "What did the Emancipation Proclamation do?",
    answer: "freed the slaves",
    topic: "American History: 1800s",
  },
  {
    id: 77,
    question: "What did Susan B. Anthony do?",
    answer: "fought for women’s rights",
    topic: "American History: Recent and Other",
  },
  {
    id: 78,
    question: "Name one war fought by the United States in the 1900s.",
    answer: "World War I",
    topic: "American History: Recent and Other",
  },
  {
    id: 79,
    question: "Who was the President during World War I?",
    answer: "Woodrow Wilson",
    topic: "American History: Recent and Other",
  },
  {
    id: 80,
    question: "Who was the President during the Great Depression and World War II?",
    answer: "Franklin Roosevelt",
    topic: "American History: Recent and Other",
  },
  {
    id: 81,
    question: "Who did the United States fight in World War II?",
    answer: "Japan, Germany, and Italy",
    topic: "American History: Recent and Other",
  },
  {
    id: 82,
    question: "Before he was President, Eisenhower was a general. What war was he in?",
    answer: "World War II",
    topic: "American History: Recent and Other",
  },
  {
    id: 83,
    question: "During the Cold War, what was the main concern of the United States?",
    answer: "Communism",
    topic: "American History: Recent and Other",
  },
  {
    id: 84,
    question: "What movement tried to end racial discrimination?",
    answer: "civil rights movement",
    topic: "American History: Recent and Other",
  },
  {
    id: 85,
    question: "What did Martin Luther King, Jr. do?",
    answer: "fought for civil rights",
    topic: "American History: Recent and Other",
  },
  {
    id: 86,
    question: "What major event happened on September 11, 2001, in the United States?",
    answer: "Terrorists attacked the United States",
    topic: "American History: Recent and Other",
  },
  {
    id: 87,
    question: "Name one American Indian tribe in the United States.",
    answer: "the Navajo tribe",
    topic: "American History: Colonial and Independence",
  },
  {
    id: 88,
    question: "Name one of the two longest rivers in the United States.",
    answer: "Mississippi River",
    topic: "Integrated Civics",
  },
  {
    id: 89,
    question: "What ocean is on the West Coast of the United States?",
    answer: "Pacific Ocean",
    topic: "Integrated Civics",
  },
  {
    id: 90,
    question: "What ocean is on the East Coast of the United States?",
    answer: "Atlantic Ocean",
    topic: "Integrated Civics",
  },
  {
    id: 91,
    question: "Name one U.S. territory.",
    answer: "Puerto Rico",
    topic: "Integrated Civics",
  },
  {
    id: 92,
    question: "Name one state that borders Canada.",
    answer: "Alaska",
    topic: "Integrated Civics",
  },
  {
    id: 93,
    question: "Name one state that borders Mexico.",
    answer: "California",
    topic: "Integrated Civics",
  },
  {
    id: 94,
    question: "What is the capital of the United States?",
    answer: "Washington, D.C.",
    topic: "Integrated Civics",
  },
  {
    id: 95,
    question: "Where is the Statue of Liberty?",
    answer: "In New York",
    topic: "Integrated Civics",
  },
  {
    id: 96,
    question: "Why does the flag have 13 stripes?",
    answer: "because there were 13 original colonies",
    topic: "Integrated Civics",
  },
  {
    id: 97,
    question: "Why does the flag have 50 stars?",
    answer: "because there are 50 states",
    topic: "Integrated Civics",
  },
  {
    id: 98,
    question: "What is the name of the national anthem?",
    answer: "The Star-Spangled Banner",
    topic: "Integrated Civics",
  },
  {
    id: 99,
    question: "When do we celebrate Independence Day?",
    answer: "July 4",
    topic: "Integrated Civics",
  },
  {
    id: 100,
    question: "Name two national U.S. holidays.",
    answer: "Thanksgiving, Christmas",
    topic: "Integrated Civics",
  },
];

export const TOPICS = [
  ...new Set(ALL_QUESTIONS.map(q => q.topic)),
];

    